#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Optional Wokwi CLI smoke (Espressif third-party tool).

Official:
  https://docs.espressif.com/projects/esp-idf/zh_CN/latest/esp32s3/third-party-tools/wokwi.html
  https://wokwi.com/
  https://docs.wokwi.com/wokwi-ci/getting-started

Exit:
  0  wokwi-cli ran and matched expect (or --dry-run wrote config)
  1  simulation failed / expect not met
  2  missing CLI, token, or firmware
  3  dry-run / list only

Not a product gate. Host SIL remains agent_gate.
"""

from __future__ import annotations

import argparse
import json
import os
import shutil
import subprocess
import sys
from pathlib import Path
from typing import List, Optional

from startup_log_oracle import analyze_startup_log


FZ_ROOT = Path(__file__).resolve().parent.parent
WOKWI_DIR = Path(__file__).resolve().parent / "wokwi"
RESULTS = FZ_ROOT / "results" / "wokwi"


def classify_cloud_error(exit_code: int, stdout: str, stderr: str) -> Optional[str]:
    cli_text = f"{stdout}\n{stderr}".lower()
    if "unauthorized" in cli_text:
        return "unauthorized"
    if exit_code != 0 and any(marker in cli_text for marker in (
        "before secure tls connection was established", "transport closed unexpectedly",
        "getaddrinfo enotfound", "getaddrinfo eai_again",
    )):
        return "transport"
    if exit_code == 42:
        return "timeout"
    return None


def find_wokwi_cli() -> Optional[str]:
    for name in ("wokwi-cli", "wokwi-cli.exe", "wokwi-cli.cmd"):
        w = shutil.which(name)
        if w:
            return w
    # Official Windows installer: %USERPROFILE%\.wokwi\bin\wokwi-cli.exe
    home = Path(os.environ.get("USERPROFILE") or os.environ.get("HOME") or "")
    for p in (
        home / ".wokwi" / "bin" / "wokwi-cli.exe",
        home / ".wokwi" / "bin" / "wokwi-cli",
        Path("C:/Users/zhugu/.wokwi/bin/wokwi-cli.exe"),
    ):
        if p.is_file():
            return str(p)
    return None


def resolve_firmware(grbl_root: Path) -> tuple[Optional[Path], Optional[Path]]:
    build = grbl_root / ".pio" / "build" / "release"
    bin_p = build / "firmware.bin"
    elf_p = build / "firmware.elf"
    if not bin_p.is_file():
        return None, None
    return bin_p, elf_p if elf_p.is_file() else None


def write_wokwi_toml(firmware: Path, elf: Optional[Path], out_dir: Path, full_flash: Optional[Path] = None) -> Path:
    """装载与当前应用一致的完整 flash，避免模拟器替换启动程序和分区表。"""
    full_flash = full_flash or firmware.with_name(firmware.stem + "_full_0x0.bin")
    partitions = firmware.with_name("partitions.bin")
    if not full_flash.is_file() or not partitions.is_file():
        raise ValueError("complete PlatformIO flash artifacts required")
    image = full_flash.read_bytes()
    application = firmware.read_bytes()
    table = partitions.read_bytes()
    if (not application or not table or image[0x1000:0x1001] != b"\xe9"
            or image[0x10000:0x10000 + len(application)] != application
            or image[0x8000:0x8000 + len(table)] != table):
        raise ValueError("complete flash does not match current application/partitions")
    out_dir.mkdir(parents=True, exist_ok=True)
    fw_src = full_flash.resolve()
    elf_src = elf.resolve() if elf and elf.is_file() else None
    fw_dst = out_dir / "firmware.bin"
    elf_dst = out_dir / "firmware.elf"
    shutil.copy2(fw_src, fw_dst)
    # 官方 flasher_args.json 接口显式从 0x0 加载；禁止把整片映像当 app 偏移猜测。
    (out_dir / "flasher_args.json").write_text(
        json.dumps({"flash_files": {"0x0": "firmware.bin"}}, indent=2) + "\n",
        encoding="utf-8",
    )
    if elf_src and elf_src.is_file():
        shutil.copy2(elf_src, elf_dst)
    else:
        # elf optional for some boards; keep key for tooling
        elf_dst.write_bytes(b"")
    text = """# auto-generated by run_wokwi_smoke.py — do not commit secrets
# Espressif: https://docs.espressif.com/projects/esp-idf/zh_CN/latest/esp32s3/third-party-tools/wokwi.html

[wokwi]
version = 1
firmware = 'flasher_args.json'
elf = 'firmware.elf'
rfc2217ServerPort = 4000
"""
    path = out_dir / "wokwi.toml"
    path.write_text(text, encoding="utf-8")
    diagram_src = WOKWI_DIR / "diagram.json"
    diagram_dst = out_dir / "diagram.json"
    if diagram_src.is_file():
        diagram_dst.write_text(diagram_src.read_text(encoding="utf-8"), encoding="utf-8")
    return path


def main(argv: Optional[List[str]] = None) -> int:
    ap = argparse.ArgumentParser(description="Wokwi CLI smoke (optional chip path)")
    ap.add_argument(
        "--grbl-root",
        type=Path,
        default=Path(os.environ.get("GRBL_ROOT", "D:/Users/Grbl_Esp32")),
    )
    ap.add_argument("--timeout-ms", type=int, default=20000)
    ap.add_argument(
        "--expect-text",
        default="['$' for help]",
        help="完整观察窗内必须出现的就绪标记，不传给 CLI 提前结束",
    )
    ap.add_argument(
        "--fail-text",
        default="Guru Meditation",
        help="fail if serial contains this",
    )
    ap.add_argument(
        "--dry-run",
        action="store_true",
        help="only write wokwi.toml under results/wokwi; do not call CLI",
    )
    ap.add_argument(
        "--require",
        action="store_true",
        help="exit 2 if CLI/token/firmware missing (default: soft message)",
    )
    ap.add_argument("--flash", type=Path, help="本次目标完整映像，仍逐字节核对应用/分区")
    args = ap.parse_args(argv)
    if args.timeout_ms <= 0 or not args.expect_text.strip():
        ap.error("观察时长必须为正，就绪标记不能为空")

    cli = find_wokwi_cli()
    token = os.environ.get("WOKWI_CLI_TOKEN", "").strip()
    bin_p, elf_p = resolve_firmware(args.grbl_root)

    report = {
        "suite": "wokwi_smoke",
        "fidelity": "optional_chip_board_sim_not_product_gate",
        "docs": [
            "https://docs.espressif.com/projects/esp-idf/zh_CN/latest/esp32s3/third-party-tools/wokwi.html",
            "https://wokwi.com/",
            "https://docs.wokwi.com/wokwi-ci/getting-started",
        ],
        "wokwi_cli": cli,
        "token_set": bool(token),
        "firmware": str(bin_p) if bin_p else None,
        "elf": str(elf_p) if elf_p else None,
        "claims_forbidden": [
            "paper_path_verified",
            "bt_verified",
            "agent_gate_replaced",
            "product_release_ok",
        ],
    }

    if not bin_p:
        print(
            "ERROR: firmware.bin not found under GRBL_ROOT .pio/build — pio run first",
            file=sys.stderr,
        )
        report["error"] = "no_firmware"
        RESULTS.mkdir(parents=True, exist_ok=True)
        (RESULTS / "wokwi_smoke_report.json").write_text(
            json.dumps(report, indent=2) + "\n", encoding="utf-8"
        )
        return 2 if args.require else 2

    work = RESULTS
    try:
        write_wokwi_toml(bin_p, elf_p, work, args.flash)
    except (OSError, ValueError) as exc:
        report.update(status="fail", error="incomplete_flash", detail=str(exc))
        work.mkdir(parents=True, exist_ok=True)
        (work / "wokwi_smoke_report.json").write_text(
            json.dumps(report, indent=2) + "\n", encoding="utf-8"
        )
        print("ERROR: rebuild the complete PlatformIO flash artifacts", file=sys.stderr)
        return 1
    report["full_flash"] = str((args.flash or bin_p.with_name(bin_p.stem + "_full_0x0.bin")).resolve())
    report["work_dir"] = str(work)
    print(f"wrote {work / 'wokwi.toml'}")
    print(f"diagram: {work / 'diagram.json'}")

    if args.dry_run:
        report["status"] = "dry_run"
        (RESULTS / "wokwi_smoke_report.json").write_text(
            json.dumps(report, indent=2) + "\n", encoding="utf-8"
        )
        print("dry-run only — install wokwi-cli and set WOKWI_CLI_TOKEN to simulate")
        return 0

    if not cli:
        print(
            "ERROR: wokwi-cli not found\n"
            "  Install: .\\chip_sim\\install_wokwi_windows.ps1\n"
            "  Or: https://docs.wokwi.com/wokwi-ci/cli-installation\n"
            "  Browser (no CLI): https://wokwi.com/",
            file=sys.stderr,
        )
        report["error"] = "no_cli"
        report["status"] = "skipped"
        (RESULTS / "wokwi_smoke_report.json").write_text(
            json.dumps(report, indent=2) + "\n", encoding="utf-8"
        )
        return 2 if args.require else 0

    if not token:
        print(
            "SKIP: WOKWI_CLI_TOKEN not set — CLI simulate needs a token.\n"
            "  1) Login https://wokwi.com/dashboard/ci  → Create token\n"
            "  2) $env:WOKWI_CLI_TOKEN='...'\n"
            "  3) Or permanent: "
            "[Environment]::SetEnvironmentVariable('WOKWI_CLI_TOKEN','...','User')\n"
            "  Config already written under results/wokwi/ — ready when token is set.\n"
            "  Browser without token: https://wokwi.com/",
            file=sys.stderr,
        )
        report["error"] = "no_token"
        report["status"] = "skipped_no_token"
        (RESULTS / "wokwi_smoke_report.json").write_text(
            json.dumps(report, indent=2) + "\n", encoding="utf-8"
        )
        return 2 if args.require else 0

    cmd = [
        cli,
        str(work),
        "--timeout",
        str(args.timeout_ms),
        "--serial-log-file",
        str(work / "serial.log"),
    ]
    # CLI 的 expect-text 命中即退出，早期版本标题不能证明后续初始化。
    # 独立退出码证明观察窗走完；仍必须通过就绪/异常串口判定。
    cmd.extend(["--timeout-exit-code", "43"])
    serial_log = work / "serial.log"
    serial_log.write_text("", encoding="utf-8")
    if args.fail_text:
        cmd.extend(["--fail-text", args.fail_text])

    print("RUN:", " ".join(cmd))
    env = os.environ.copy()
    env["WOKWI_CLI_TOKEN"] = token
    try:
        proc = subprocess.run(cmd, cwd=str(work), env=env, capture_output=True, text=True,
                              errors="replace", timeout=args.timeout_ms / 1000 + 60)
    except subprocess.TimeoutExpired:
        # CLI 卡住不等于正常完成模拟观察窗，不能拿残留串口判绿。
        proc = subprocess.CompletedProcess(cmd, 124, "", "Wokwi CLI wall timeout")
    if proc.stdout:
        print(proc.stdout, end="")
    if proc.stderr:
        print(proc.stderr, end="", file=sys.stderr)
    report["exit_code"] = proc.returncode
    report["cli_stdout_tail"] = proc.stdout[-4000:]
    report["cli_stderr_tail"] = proc.stderr[-4000:]
    report["cloud_error"] = classify_cloud_error(proc.returncode, proc.stdout, proc.stderr)
    serial_log = work / "serial.log"
    serial_text = serial_log.read_text(encoding="utf-8", errors="replace") if serial_log.is_file() else ""
    startup = analyze_startup_log(serial_text, [args.expect_text] if args.expect_text else [])
    report["startup"] = startup
    # 只有启动前的鉴权/连接失败属于可选云基础设施不可用；串口已有输出、
    # 固件 panic、重启或超时不能借网络错误豁免。
    report["blocking"] = not (report["cloud_error"] in {"unauthorized", "transport"}
                              and not serial_text.strip())
    report["serial_log"] = str(serial_log)
    report["observation_complete"] = proc.returncode == 43
    report["observation_ms"] = args.timeout_ms
    report["status"] = "pass" if report["observation_complete"] and not report["cloud_error"] and startup["status"] == "pass" else "fail"
    # timeout exit 42 per Espressif idf-wokwi docs
    if proc.returncode == 42:
        report["note"] = "timeout (official exit 42)"
    (RESULTS / "wokwi_smoke_report.json").write_text(
        json.dumps(report, indent=2) + "\n", encoding="utf-8"
    )
    print(json.dumps(report, indent=2))
    print(
        "HONESTY: Wokwi green ≠ paper/BT/OTA; host SIL remains agent_gate.",
        flush=True,
    )
    return 0 if report["status"] == "pass" else 1


if __name__ == "__main__":
    raise SystemExit(main())
