#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Optional Wokwi CLI smoke (Espressif third-party tool).

Official:
  https://docs.espressif.com/projects/esp-idf/zh_CN/latest/esp32s3/third-party-tools/wokwi.html
  https://wokwi.com/
  https://docs.wokwi.com/wokwi-ci/getting-started

Exit:
  0  wokwi-cli ran and matched expect (or --dry-run wrote config)
  1  simulation failed / expect not met
  2  missing CLI, token, or firmware
  3  dry-run / list only

Not a product gate. Host SIL remains agent_gate.
"""

from __future__ import annotations

import argparse
import json
import os
import shutil
import subprocess
import sys
from pathlib import Path
from typing import List, Optional


FZ_ROOT = Path(__file__).resolve().parent.parent
WOKWI_DIR = Path(__file__).resolve().parent / "wokwi"
RESULTS = FZ_ROOT / "results" / "wokwi"


def find_wokwi_cli() -> Optional[str]:
    for name in ("wokwi-cli", "wokwi-cli.exe", "wokwi-cli.cmd"):
        w = shutil.which(name)
        if w:
            return w
    # Official Windows installer: %USERPROFILE%\.wokwi\bin\wokwi-cli.exe
    home = Path(os.environ.get("USERPROFILE") or os.environ.get("HOME") or "")
    for p in (
        home / ".wokwi" / "bin" / "wokwi-cli.exe",
        home / ".wokwi" / "bin" / "wokwi-cli",
        Path("C:/Users/zhugu/.wokwi/bin/wokwi-cli.exe"),
    ):
        if p.is_file():
            return str(p)
    return None


def resolve_firmware(grbl_root: Path) -> tuple[Optional[Path], Optional[Path]]:
    build = grbl_root / ".pio" / "build" / "release"
    bin_p = build / "firmware.bin"
    elf_p = build / "firmware.elf"
    if not bin_p.is_file():
        bins = list((grbl_root / ".pio" / "build").glob("*/firmware.bin")) if (
            grbl_root / ".pio" / "build"
        ).is_dir() else []
        if bins:
            bin_p = bins[0]
            elf_p = bin_p.with_suffix(".elf")
    if not bin_p.is_file():
        return None, None
    return bin_p, elf_p if elf_p.is_file() else None


def write_wokwi_toml(firmware: Path, elf: Optional[Path], out_dir: Path) -> Path:
    """Copy firmware into out_dir; wokwi-cli resolves paths relative to project dir."""
    out_dir.mkdir(parents=True, exist_ok=True)
    fw_src = firmware.resolve()
    elf_src = elf.resolve() if elf and elf.is_file() else None
    fw_dst = out_dir / "firmware.bin"
    elf_dst = out_dir / "firmware.elf"
    shutil.copy2(fw_src, fw_dst)
    if elf_src and elf_src.is_file():
        shutil.copy2(elf_src, elf_dst)
    elif not elf_dst.is_file():
        # elf optional for some boards; keep key for tooling
        elf_dst.write_bytes(b"")
    text = """# auto-generated by run_wokwi_smoke.py — do not commit secrets
# Espressif: https://docs.espressif.com/projects/esp-idf/zh_CN/latest/esp32s3/third-party-tools/wokwi.html

[wokwi]
version = 1
firmware = 'firmware.bin'
elf = 'firmware.elf'
rfc2217ServerPort = 4000
"""
    path = out_dir / "wokwi.toml"
    path.write_text(text, encoding="utf-8")
    diagram_src = WOKWI_DIR / "diagram.json"
    diagram_dst = out_dir / "diagram.json"
    if diagram_src.is_file():
        diagram_dst.write_text(diagram_src.read_text(encoding="utf-8"), encoding="utf-8")
    return path


def main(argv: Optional[List[str]] = None) -> int:
    ap = argparse.ArgumentParser(description="Wokwi CLI smoke (optional chip path)")
    ap.add_argument(
        "--grbl-root",
        type=Path,
        default=Path(os.environ.get("GRBL_ROOT", "D:/Users/Grbl_Esp32")),
    )
    ap.add_argument("--timeout-ms", type=int, default=20000)
    ap.add_argument(
        "--expect-text",
        default="",
        help="success if serial contains this (official CLI flag)",
    )
    ap.add_argument(
        "--fail-text",
        default="Guru Meditation",
        help="fail if serial contains this",
    )
    ap.add_argument(
        "--dry-run",
        action="store_true",
        help="only write wokwi.toml under results/wokwi; do not call CLI",
    )
    ap.add_argument(
        "--require",
        action="store_true",
        help="exit 2 if CLI/token/firmware missing (default: soft message)",
    )
    args = ap.parse_args(argv)

    cli = find_wokwi_cli()
    token = os.environ.get("WOKWI_CLI_TOKEN", "").strip()
    bin_p, elf_p = resolve_firmware(args.grbl_root)

    report = {
        "suite": "wokwi_smoke",
        "fidelity": "optional_chip_board_sim_not_product_gate",
        "docs": [
            "https://docs.espressif.com/projects/esp-idf/zh_CN/latest/esp32s3/third-party-tools/wokwi.html",
            "https://wokwi.com/",
            "https://docs.wokwi.com/wokwi-ci/getting-started",
        ],
        "wokwi_cli": cli,
        "token_set": bool(token),
        "firmware": str(bin_p) if bin_p else None,
        "elf": str(elf_p) if elf_p else None,
        "claims_forbidden": [
            "paper_path_verified",
            "bt_verified",
            "agent_gate_replaced",
            "product_release_ok",
        ],
    }

    if not bin_p:
        print(
            "ERROR: firmware.bin not found under GRBL_ROOT .pio/build — pio run first",
            file=sys.stderr,
        )
        report["error"] = "no_firmware"
        RESULTS.mkdir(parents=True, exist_ok=True)
        (RESULTS / "wokwi_smoke_report.json").write_text(
            json.dumps(report, indent=2) + "\n", encoding="utf-8"
        )
        return 2 if args.require else 2

    work = RESULTS
    write_wokwi_toml(bin_p, elf_p, work)
    report["work_dir"] = str(work)
    print(f"wrote {work / 'wokwi.toml'}")
    print(f"diagram: {work / 'diagram.json'}")

    if args.dry_run:
        report["status"] = "dry_run"
        (RESULTS / "wokwi_smoke_report.json").write_text(
            json.dumps(report, indent=2) + "\n", encoding="utf-8"
        )
        print("dry-run only — install wokwi-cli and set WOKWI_CLI_TOKEN to simulate")
        return 0

    if not cli:
        print(
            "ERROR: wokwi-cli not found\n"
            "  Install: .\\chip_sim\\install_wokwi_windows.ps1\n"
            "  Or: https://docs.wokwi.com/wokwi-ci/cli-installation\n"
            "  Browser (no CLI): https://wokwi.com/",
            file=sys.stderr,
        )
        report["error"] = "no_cli"
        report["status"] = "skipped"
        (RESULTS / "wokwi_smoke_report.json").write_text(
            json.dumps(report, indent=2) + "\n", encoding="utf-8"
        )
        return 2 if args.require else 0

    if not token:
        print(
            "SKIP: WOKWI_CLI_TOKEN not set — CLI simulate needs a token.\n"
            "  1) Login https://wokwi.com/dashboard/ci  → Create token\n"
            "  2) $env:WOKWI_CLI_TOKEN='...'\n"
            "  3) Or permanent: "
            "[Environment]::SetEnvironmentVariable('WOKWI_CLI_TOKEN','...','User')\n"
            "  Config already written under results/wokwi/ — ready when token is set.\n"
            "  Browser without token: https://wokwi.com/",
            file=sys.stderr,
        )
        report["error"] = "no_token"
        report["status"] = "skipped_no_token"
        (RESULTS / "wokwi_smoke_report.json").write_text(
            json.dumps(report, indent=2) + "\n", encoding="utf-8"
        )
        return 2 if args.require else 0

    cmd = [
        cli,
        str(work),
        "--timeout",
        str(args.timeout_ms),
        "--serial-log-file",
        str(work / "serial.log"),
    ]
    if args.expect_text:
        cmd.extend(["--expect-text", args.expect_text])
    if args.fail_text:
        cmd.extend(["--fail-text", args.fail_text])

    print("RUN:", " ".join(cmd))
    env = os.environ.copy()
    env["WOKWI_CLI_TOKEN"] = token
    proc = subprocess.run(cmd, cwd=str(work), env=env)
    report["exit_code"] = proc.returncode
    report["status"] = "pass" if proc.returncode == 0 else "fail"
    # timeout exit 42 per Espressif idf-wokwi docs
    if proc.returncode == 42:
        report["note"] = "timeout (official exit 42)"
    (RESULTS / "wokwi_smoke_report.json").write_text(
        json.dumps(report, indent=2) + "\n", encoding="utf-8"
    )
    print(json.dumps(report, indent=2))
    print(
        "HONESTY: Wokwi green ≠ paper/BT/OTA; host SIL remains agent_gate.",
        flush=True,
    )
    return 0 if proc.returncode == 0 else 1


if __name__ == "__main__":
    raise SystemExit(main())
